# Generated by Selenium IDE
# Implementar una descripción extensa en la biografía del perfil en TUCAN - Usuario
import pytest
import time
import json
import csv
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestCP007N():
  def setup_method(self):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self):
    self.driver.quit()
  
  def test_cP007N(self, email, password):
    self.driver.get("https://tucan.toolsincloud.net/index.php")
    self.driver.set_window_size(1382, 736)
    self.driver.find_element(By.NAME, "email").click()
    self.driver.find_element(By.NAME, "email").send_keys(email)
    self.driver.find_element(By.NAME, "password").click()
    self.driver.find_element(By.NAME, "password").send_keys(password)
    self.driver.find_element(By.NAME, "login").click()
    self.driver.find_element(By.CSS_SELECTOR, ".grid-sidebar:nth-child(7) strong").click()
    self.driver.find_element(By.CSS_SELECTOR, ".home-edit-button").click()
    self.driver.find_element(By.NAME, "bio").clear()
    self.driver.find_element(By.NAME, "bio").click()
    self.driver.find_element(By.NAME, "bio").send_keys("La Luna es el único satélite natural de la Tierra. Con un diámetro ecuatorial   de 3474.8 km, es el quinto satélite más grande del sistema solar, mientras que en cuanto al tamaño proporcional respecto a su planeta es el satélite más grande: un cuarto del diámetro de la Tierra y 1/81 de su masa. Es, además, después de Ío, el segundo satélite más denso. Se encuentra en relación síncrona con la Tierra, siempre mostrando la misma cara hacia el planeta. El hemisferio visible está marcado con oscuros mares lunares de origen volcánico entre las brillantes montañas antiguas y los destacados astroblemas.")
    self.driver.find_element(By.NAME, "update").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".text-center:nth-child(1)").text == "bio must be less than 100 chars"
    
  def exeCP007N(self):
    try:
      self.test007n = TestCP007N()
      with open("registros.csv") as c:
         self.reader=csv.DictReader(c)
         for row in self.reader:
          self.test007n.setup_method()
          self.test007n.test_cP007N(email=row["email"], password=row["password"])
          self.test007n.teardown_method()
          print("Descripción extensa en la biografía del perfil",row["id"],"hecha correctamente.")
    except:
      print("Algo inesperado ha ocurrido en el CP007N")
        
exe = TestCP007N()
exe.exeCP007N()