# Generated by Selenium IDE
# Implementar una descripción en la biografía del perfil en TUCAN - Usuario
import pytest
import time
import json
import csv
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestCP007P():
  def setup_method(self):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self):
    self.driver.quit()
  
  def test_cP007P(self, email, password):
    self.driver.get("https://tucan.toolsincloud.net/index.php")
    self.driver.set_window_size(1382, 736)
    self.driver.find_element(By.NAME, "email").click()
    self.driver.find_element(By.NAME, "email").send_keys(email)
    self.driver.find_element(By.NAME, "password").click()
    self.driver.find_element(By.NAME, "password").send_keys(password)
    self.driver.find_element(By.NAME, "login").click()
    self.driver.find_element(By.CSS_SELECTOR, ".grid-sidebar:nth-child(7) strong").click()
    self.driver.find_element(By.CSS_SELECTOR, ".home-edit-button").click()
    self.driver.find_element(By.NAME, "bio").clear()
    self.driver.find_element(By.NAME, "bio").click()
    self.driver.find_element(By.NAME, "bio").send_keys("Realizando pruebas para ingeniera de software ")
    self.driver.find_element(By.NAME, "update").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".bio").text == "Realizando pruebas para ingeniera de software"
  
  def exeCP007P(self):
    try:
      self.test007p = TestCP007P()
      with open("registros.csv") as c:
        self.reader=csv.DictReader(c)
        for row in self.reader:
          self.test007p.setup_method()
          self.test007p.test_cP007P(email=row["email"], password=row["password"])
          self.test007p.teardown_method()
          print("Descripción en la biografía del perfil",row["id"],"hecha correctamente.")
    except:
      print("Algo inesperado ha ocurrido en el CP007P")
      
exe = TestCP007P()
exe.exeCP007P()